version: 2.1
orbs:
  node: circleci/node@5.0.2  #node version in circleci
  aws-cli: circleci/aws-cli@2.0.0 #aws command line interface version in circleci
jobs:
  frontend:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup:  #Defining the AWS IAM user
          profile-name: cli_user
      - run:
          #install frontend dependencies
          name: Front-End Install
          command: | 
            npm run frontend:install  
      - run:
          #build frontend code (www)
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          #host frontend application
          name: Deploy App
          command: |
            npm run frontend:deploy
  server:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup:  #Defining the AWS IAM user
          profile-name: cli_user
      - run:
          name: Install pip
          command: |
            sudo apt update
            sudo apt install -y python3-pip python-dev
      - run:
          name: Install AWS dependencies
          command: |
            sudo pip install awsebcli
      - run:
          #install frontend dependencies
          name: Back-End Install
          command: | 
            npm run backend:install  
      - run:
          #build backend code (www)
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          #Set enviroment variables on elastic beanstalk 
          name: Set enviroment variables
          command: |
            npm run backend:setenv
      - run:
          #deploy server so that it can be connected with frontend
          name: Deploy Server
          command: |
            npm run backend:deploy
workflows:
  my_workflow:
    jobs:
      - frontend
      - server
