version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@2.0.0
jobs:
  frontend:
    working_directory:  ../udagram-frontend
    executor: node/default
    steps:
  server:
    working_directory: ../udagram-api
    executor: node/default
    steps:
workflows:
  build_and_deploy:
    jobs:
      - frontend
      - server
